package com.encryptorDecryptor.enums;

public enum EncryptionEventEnum {
	ENCRYPTION_STARTED,
	ENCRYPTION_ENDED,
	DECRYPTION_STARTED,
	DECRYPTION_ENDED, 
	DIRECTORY_ENCRYPTION_STARTED,
	DIRECTORY_ENCRYPTION_ENDED,
	DIRECTORY_DECRYPTION_STARTED,
	DIRECTORY_DECRYPTION_ENDED
}
